---
# Sample task 1: creating a new user

- name: Create new user
  win_shell: |
    net user {{ win_user }} {{ win_password }} /add
    net localgroup Administrators {{ win_user }} /add
  register: output
  ignore_errors: true
